[package]
name = "qi_rust"
version = "0.1.0"
authors = ["Xuanwo <github@xuanwo.io>"]
edition = "2018"

[dependencies]
qi_openapi = {path="../qi_openapi"}
clap = "2.33.2"
serde = { version = "1.0.114", features = ["derive"] }
handlebars = "3.3.0"
serde_json = "1.0.57"
serde_yaml = "0.8.13"
